Update Jwt.cs
Without this build v4 bot results in the following error. 
\Jwt.cs(27,46): error CS0246: The type or namespace name 'NewtonsoftMapper' could not be found (are you missing a using directive or an assembly reference?) 
\Jwt.cs(60,50): error CS0246: The type or namespace name 'NewtonsoftMapper' could not be found (are you missing a using directive or an assembly reference?) [